### ISSUE TITLE
Checker icon bug: "Cannot tween null target"

### ISSUE THREAD

**Issue by andrewbarden** [conversationai/perspectiveapi-authorship-demo#26]
While testing, we've discovered a bug in a specific checker component journey on the Perspective API website. 

## Repro
1. Type something into the authorship demo
2. Click "Seem Wrong?"
3. Click Yes or No
4. Click the checker icon, and observe error `core.es5.js:1020 ERROR Cannot tween a null target.`

## References
![screenshot 2017-11-17 11 20 02](https://user-images.githubusercontent.com/13004318/32965057-31a5d992-cb8a-11e7-92e5-fc5bb8a6e087.png)
![screenshot 2017-11-17 11 20 04](https://user-images.githubusercontent.com/13004318/32965058-31c008f8-cb8a-11e7-98d8-74fea76e1d00.png)
![screenshot 2017-11-17 11 20 07](https://user-images.githubusercontent.com/13004318/32965059-31d98d50-cb8a-11e7-947a-4fdbb7b06ded.png)
![screenshot 2017-11-17 11 20 09](https://user-images.githubusercontent.com/13004318/32965060-31f0e02c-cb8a-11e7-9757-bebb0a0f3816.png)

**Comment by andrewbarden** [comment]
@rachelrosengoogle looks like I can't assign issues in your repo, but reported a bug for you!

**Comment by rachelrosengoogle** [comment]
Thanks for letting me know! I'll take a look soon.

**Comment by rachelrosengoogle** [comment]
Would you mind sharing the exact DemoSettings that were being passed when this bug occurred? Or does this occur for all settings? I'll try to add a test for this case as well.

**Comment by andrewbarden** [comment]
Within the marketing site UI, it happens with all settings.

**Comment by rachelrosengoogle** [comment]
Thanks. One more thing--confirm the npm version being used when this happens?

**Comment by andrewbarden** [comment]
Sure thing, we're using 0.4.1. We had bumped to 0.4.3 but were getting errors, so didn't merge it in.

**Comment by rachelrosengoogle** [comment]
What were the errors you were getting in 0.4.3? The code is in a pretty different state right now than it was for 0.4.1. Send me an email or file an issue with the other errors, since that's pretty important.

Also, which branch on the repo are you working from? I tried from master but still see the old version.

**Comment by rachelrosengoogle** [comment]
It might be easier if we can jump on a chat for 5-10 minutes to work this out, so I know which direction to go in.

**Comment by rachelrosengoogle** [comment]
Closing this as obsolete, since the icon is no longer clickable.
